//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubNet.WebSite.Resources.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClubNet.WebSite.Resources.Controllers.UserController", typeof(UserController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street and number.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complement.
        /// </summary>
        internal static string AddressComplement {
            get {
                return ResourceManager.GetString("AddressComplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Place.
        /// </summary>
        internal static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        internal static string ContactInfo {
            get {
                return ResourceManager.GetString("ContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        internal static string FemmeShort {
            get {
                return ResourceManager.GetString("FemmeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By checking this box you are agree with the club rules and you confirm that your GDRP choice have been made in all knowledge of the implication..
        /// </summary>
        internal static string GDRPHaveBeenReaded {
            get {
                return ResourceManager.GetString("GDRPHaveBeenReaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You allow the club to use your image in an internal usage, mail communication, internal site pages, internal display in the club application, ....
        /// </summary>
        internal static string GDRPImageInternalUsage {
            get {
                return ResourceManager.GetString("GDRPImageInternalUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You allow the club to use your image in an public usage controlled by the club. communication through the social networks, public mail ads, web site public articles, ....
        /// </summary>
        internal static string GDRPImagePublicUsage {
            get {
                return ResourceManager.GetString("GDRPImagePublicUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDRP : Data usage right.
        /// </summary>
        internal static string GDRPInfo {
            get {
                return ResourceManager.GetString("GDRPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You allow the club to use your first and last name in an internal usage, mail communication, internal site pages, internal display in the club application, ....
        /// </summary>
        internal static string GDRPNameInternalUsage {
            get {
                return ResourceManager.GetString("GDRPNameInternalUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You allow the club to use your first and last name in an public usage controller by the club. communication through the social networks, public mail ads, web site public articles, ....
        /// </summary>
        internal static string GDRPNamePublicUsage {
            get {
                return ResourceManager.GetString("GDRPNamePublicUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since 2018 in european law ask all the system that store user information to inform the usage of it. By the following checks you allow or not your informations to be used in a specific context..
        /// </summary>
        internal static string GDRPSummary {
            get {
                return ResourceManager.GetString("GDRPSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string HommeShort {
            get {
                return ResourceManager.GetString("HommeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club member Id.
        /// </summary>
        internal static string MemberNumber {
            get {
                return ResourceManager.GetString("MemberNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Subscription.
        /// </summary>
        internal static string NewSubscription {
            get {
                return ResourceManager.GetString("NewSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Information.
        /// </summary>
        internal static string PlayerInfo {
            get {
                return ResourceManager.GetString("PlayerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexe.
        /// </summary>
        internal static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administratif Support.
        /// </summary>
        internal static string SubscriptionRole_AdministratifSupport {
            get {
                return ResourceManager.GetString("SubscriptionRole_AdministratifSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string SubscriptionRole_Player {
            get {
                return ResourceManager.GetString("SubscriptionRole_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refere.
        /// </summary>
        internal static string SubscriptionRole_Refere {
            get {
                return ResourceManager.GetString("SubscriptionRole_Refere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Official.
        /// </summary>
        internal static string SubscriptionRole_TableOfficial {
            get {
                return ResourceManager.GetString("SubscriptionRole_TableOfficial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainer.
        /// </summary>
        internal static string SubscriptionRole_Trainer {
            get {
                return ResourceManager.GetString("SubscriptionRole_Trainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer.
        /// </summary>
        internal static string SubscriptionRole_Volunteer {
            get {
                return ResourceManager.GetString("SubscriptionRole_Volunteer", resourceCulture);
            }
        }
    }
}
